// Loadding bar
export const SET_LOADDING = "SET_LOADDING";

// User
export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

// Subject
export const GET_ALL_SUBJECT = "GET_ALL_SUBJECT";

// Sub Subject
export const GET_ALL_SUBSUBJECT = "GET_ALL_SUBSUBJECT";

// Teacher
export const GET_ALL_TEACHER = "GET_ALL_TEACHER";
export const ADD_NEW_TEACHER = "ADD_NEW_TEACHER";
export const UPDATE_TEACHER_INFO = "UPDATE_TEACHER_INFO";
export const DELETE_TEACHER = "DELETE_TEACHER";

// Classroom
export const GET_ALL_CLASSROOM = "GET_ALL_CLASSROOM";
export const ADD_NEW_CLASSROOM = "ADD_NEW_CLASSROOM";
export const UPDATE_CLASSROOM_INFO = "UPDATE_CLASSROOM_INFO";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";

// Student Studying
export const GET_ALL_STUDENT_STUDYING = "GET_ALL_STUDENT_STUDYING";
export const ADD_NEW_STUDENT_STUDYING = "ADD_NEW_STUDENT_STUDYING";
export const UPDATE_STUDENT_STUDYING_INFO = "UPDATE_STUDENT_STUDYING_INFO";
export const DELETE_STUDENT_STUDYING = "DELETE_STUDENT_STUDYING";
