export const SET_LOADDING = "SET_LOADDING";

export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const GET_ALL_SUBJECT = "GET_ALL_SUBJECT";

export const GET_ALL_SUBSUBJECT = "GET_ALL_SUBSUBJECT";
